CONFIG <- list(
  is_primary = TRUE,
  offices = c(
    "CITY COMMISSIONERS-DEM",
    "COUNCIL AT LARGE-DEM",
    "DISTRICT COUNCIL-2ND DISTRICT-DEM",
    "DISTRICT COUNCIL-3RD DISTRICT-DEM",
    "DISTRICT COUNCIL-7TH DISTRICT-DEM",
    "MAYOR-DEM"
  ),
  use_log=TRUE
)
